# LambdaTest Configuration

# Project and folder configuration
project_id: "01KT9NFKS2WT697GF4XJTTKA4K"
folder_id: "01KVTTA62HGXSP5AJKTQ9QMPWH"

# Test Run configuration
assignee: 427758
environment_id: 505

# Test URL for automation
# test_url: "https://demo.lambdatestinternal.com"
